version: "3.9"
   
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/Picha
    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: sh -c "cd ./picha-frontend && npm install && npm start"
    volumes:
      - .:/Picha/frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend
  worker:
    build: .
    command: 'celery -A picha worker -l info'
    volumes: 
      - .:/Picha
    depends_on: 
      - redis
      - db
  beat:
      build: .  
      command: 'celery -A picha beat -l info'
      volumes: 
        - .:/Picha
      depends_on:
        - redis
        - db  