version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  backend:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate; python manage.py runserver 0.0.0.0:8000'

    volumes:
      - .:/picha-petrec
    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis

  worker:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; celery -A picha worker -l info'
    volumes: 
      - .:/picha-petrec
    depends_on: 
      - redis
      - db
      - backend
  beat:
      build: .  
      command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; celery -A picha beat -l info'
      volumes: 
        - .:/picha-petrec
      depends_on:
        - redis
        - worker
        - db  

  frontend:
        build:
          context: frontend
          dockerfile: Dockerfile
        command: sh -c "cd ./picha-frontend && npm install && npm start"
        volumes:
          - .:/picha-petrec/frontend/
        ports:
            - "3000:3000"
        depends_on:
          - db
          - backend